def executor_agent(test_info: dict)-> dict:
    """
    This function takes the test plan generated by the tester agent and executes
    the tests according to the specified execution strategy.

    input :
    test_info :
        detailed_tests
        execution_strategy
        estimated_time

    output :
    test_results :
        passed_tests
        failed_tests
        logs
        summary_report

    """
    pass