import subprocess
def executor_agent(test_info: dict)-> dict:
    """
    This function takes the test plan generated by the tester agent and executes
    the tests according to the specified execution strategy.

    input :
    test_info :
        detailed_tests
        execution_strategy
        estimated_time

    output :
    test_results :
        passed_tests
        failed_tests
        logs
        summary_report

    """
    command = test_info.get("execution_strategy", "pytest")

    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            status = "pass"
            failed_tests = []
        else:
            status = "fail"
            failed_tests = ["unknown_test_failure"]  # improve later

        return {
            "passed_tests": [] if status == "fail" else ["all"],
            "failed_tests": failed_tests,
            "logs": result.stdout + result.stderr,
            "summary_report": f"Test execution {status}"
        }

    except Exception as e:
        return {
            "passed_tests": [],
            "failed_tests": ["execution_error"],
            "logs": str(e),
            "summary_report": "Executor crashed"
        }
if __name__ == "__main__":
    test_info = {
        "execution_strategy": "pytest"
    }

    output = executor_agent(test_info)
    print(output)
