def tester_agent(plan:dict)-> dict:
    """
    This function takes the plan generated by the planner agent and determines
    the appropriate tests to run based on the modules to be tested, test types,
    and risk level.

    input :
    plan :
        modules_test
        test_types
        risk_level 

    output :
    test_plan :
        detailed_tests
        execution_strategy
        estimated_time

    """
    pass